### ISSUE TITLE
Cachefiles in homefolder.

### ISSUE THREAD

**Issue by oppsig** [caronc/nzb-subliminal#37]
These three files usally always resides in my homefolder. (/home/kodi)

```
cachefile.dbm
cachefile.dbm.dogpile.lock
cachefile.dbm.rw.lock
```
Regular subliminal uses appdirs.  

nzbget is at /opt/ppscripts/nzbget-subliminal

**Comment by caronc** [comment]
Hmm... i think i'm going to need more to go on here.  Do these appear when you run the script manually? Or do they just appear after you download something?

nzbget-subliminal tries to set all of the temporary paths to what NZBGet passes it.  So it seems strange to appear in /home/kodi unless it's being executed some other way. Alternatively, you could check your NZBGet settings; specifically look in the **PATHS** section and focus on the **TempDir** path.

Also, your last comment:
> nzbget is at /opt/ppscripts/nzbget-subliminal

Do you mean nzbget is at _/opt/nzbget/ppscripts/nzbget-subliminal_?

**Comment by oppsig** [comment]
I ment that the script is at /opt/ppscripts/nzbget-subliminal.
Yeah the script gets pulled from downloads.

${MainDir}/nzb is in my path, and that variable is not the home directory.

**Comment by caronc** [comment]
Any luck with your testing? Are the files being re-created?

**Comment by caronc** [comment]
It's been a while since I've heard back.  I'm going to close this ticket since i don't believe there is any issue at this time.  Please feel free to re-open it if you have anything more to add.
