### ISSUE TITLE
Search for pt-BR subtitles

### ISSUE THREAD

**Issue by pguizeline** [caronc/nzb-subliminal#38]
Hi!

What option should I use when searching for brazilian portugue subtitles? I've tried:
`-l pt-BR, pob, pb`

The result is:
`An error occured processing the language list`

If I use "pt" I end up fetching portugues subs.

Thanks!

**Comment by caronc** [comment]
Hmm... _pt-br_ looks good; I'll have a look at the code and see what i can find out.  If you visit sites like [addic7ed](http://www.addic7ed.com/), do you see subtitles in the language you want?

If so, can you pass back a hyper-link here to some Portuguese(Brazilian) examples?  It would really help with the debugging process.

**Comment by pguizeline** [comment]
I get the error using pt-br all lowercase too. Addic7ed has pt-br subtitles, what kind of examples do you mean?

**Comment by caronc** [comment]
I was having difficulties finding examples on Addic7ed's website (but i just found one now so I'll use that as an example).  Anyway, just like your last issues: I'll try and have you something for you to try before the start of next week.

Thanks for reporting this issue!

**Comment by pguizeline** [comment]
I should be the one thanking you!! Thanks a lot for all your fast replies and don't rush! I wish I could help you more!

**Comment by caronc** [comment]
I just added a small change that will _kind of_ help you out. The way the languages are set up in the Subliminal don't really take in account for content after the hyphen.

 I added the language codes '**pb**', **pob**, and **Brazilan**. _pb_ isn't really the correct code (_pt-br_ is) so i don't know how many matches it will hit.  _pb_ IS however the Brazilian language code used on [OpenSubtitles](https://www.opensubtitles.org/pb/); so it's possible other sites use this.  I know for sure [_Addic7ed_](www.addic7ed.com) just uses **pt-br** (so you'll only hit when using **pt** here).

```python
# The following will guarantee at least a match against pb or pt if present
./Subliminal.py -l pb,pt
```

It's unfortunate, it's like the world cursed Brazilians by not giving you guys your own language code and providing it as just a subset of the Portuguese one. 😞

**Comment by pguizeline** [comment]
This is awesome!!! It's working perfectly! Thanks a lot for all your time and effort! Do you have any account that I can donate for all your work?

**Comment by caronc** [comment]
I'm glad everything is back up and going for you! You honestly don't owe me anything at all, although it's super kind of you to offer though!

Please feel free to let me know if you have any more problems. :smile:
