### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by mattmac24** [caronc/nzb-subliminal#43]
When running this script on a standard ubuntu 16.04 server I get the following error:

> ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/lib/python2.7/dist-packages

The fix I have been applying is from [this](https://forum.nzbget.net/viewtopic.php?t=1422&start=266) thread thanks to ronajon.

> easiest (and dirtiest) way is to change value '0.7' on line 2275 of file 'Subliminal/pkg_resources.py to another value. eg 0.6

I have setup nzbget-subliminal a few different times in the last few months and every time I have had to make this change before anything will work.

**Comment by caronc** [comment]
Thanks for the bug report.  I'm not quite sure how that entire conversation happened in front of me and i was oblivious to it 😕 . 

The 0.7 _setuptools_ series isn't applicable to the _Subliminal.py_ code, so it should be safe to just drop the check all together.
