### ISSUE TITLE
Standalone

### ISSUE THREAD

**Issue by JackDandy** [caronc/nzb-subliminal#49]
Hello again,

This project neatly wraps subliminal and addresses issues you found, and you are also adding auth.

One issue i see is the reliance (in cmdline mode) of a folder to scan, that data can actually not be available if 3rd-party-app has cleaned/renamed it -- however, the original names could still be available via the 3rd-party-app db, therefore, a method to simply send an original name would be useful. 

Also, I guess the app saves the state of its decisions in order to act on them at some later time, it would be useful if this state list/object could be returned for saving elsewhere and then that data pushed back to your app at a later time. This implies a "try_again_in_mins" be returned so that 3rd-party-app know when at least to schedule a next call to your app. And this way, the data to be saved on whatever device is _optionally_ managed by 3rd-party-app instead of yours.

Given that goals of this project can be enjoyed outside of NZBGET/SAB, then this project is suited to go through the same as Apprise, no?
  
JD

**Comment by caronc** [comment]
> Given that goals of this project can be enjoyed outside of NZBGET/SAB, then this project is suited to go through the same as Apprise, no?

Subliminal is not my design at all.  It's based on a very old fork of [this project](https://github.com/Diaoul/subliminal) which pretty much handles your request (i think) - Standalone.  The original developer has completely re-factored all of his old code (which i'm using).

The script as is does already track the age of the file(s) it's scanning against... so if you set up a cron to just run against your library say... every X minutes (like you're eluding to):
* it won't grab subs for files that already have them
* will gracefully look again for those that don't have subs
* it will stop looking for subs on files that are over X days.

 Perhaps I'm missing what your asking here?

**Comment by JackDandy** [comment]
Ok, I will look deeper, maybe I missed somethings.

Thank you.
