### ISSUE TITLE
Some subtitles have question marks.

### ISSUE THREAD

**Issue by bokiroki** [caronc/nzb-subliminal#50]
Some subtitles have question marks that are replacing central european characters..first i thought that problem was with subtitle writers, i thought that they didnt encoded properly files.. first i tried to put my keyboard in windows to serbian, than i tried to change in control panel/region/change system locale to serbian, then i tried to save srt file with notepad but with ansi encoding, and nothing changed..next i tried to put different encodes in your script
-n ISO-8859-2
-n ISO-8859-16 
-n ISO-8859-5
-n Windows-1250
also i tried with -e command all those encodings, and nothing
than i went to opensubtitles (i tested two movies and both srt files were downloaded in serbian and from opensubtitles with nzb subliminal) and downloaded every srt file for that movies in serbian to see will i get question marks, but every subtitles was ok..i found exact subtitles that nzb subliminal downloaded and only difference is that when subtitle is downloaded with nzb i get opensubtitles ad at the start of the subtitle, everything else is the same. here are two screenshots for you to see

https://imgur.com/pBUq3cD
https://imgur.com/56dX3Mg

on the left is subtitle i downloaded from opensubtitles, on the right is subtitle downloaded with nzb subliminal..

edit: today i downloaded 11 movies with radarr, and last six moves that were downloaded have subtitles with question marks..i saw that radarr dont put movies in folders when movie is downloaded, it was done when all movies was downloaded..so than subtitle script was started.. maybe it help

**Comment by caronc** [comment]
I'm so sorry for taking so long to get back to you.  I some how missed your original request.  It was your recent _edit_ you just made that caused GitHub to email me about this.

Anyway.. I'll take a closer look at this when i can. Maybe i could add an option to just accept the content 'as-is'.  To not manipulate it in any way after it's downloaded?

**Comment by bokiroki** [comment]
Please do that when you can.

**Comment by caronc** [comment]
The bug was on my end and it defaults to always 'tidying' your subs up.  This by default is turned off now (as it should have been from the start).

This 'should' resolve your problem.  Please check out the master and try again.  There is no need to specify the default encodings (with the -n switch).

**Comment by caronc** [comment]
Great to hear! : smile:

**Comment by bokiroki** [comment]
just few hours after i reported that i didn't found any problems, i downloaded movie with bad subtitle :smile: 
i downloaded movie with radarr, radarr called your script.. i didn't put any -n and -e (encodings in script)
and i got the same question marks on special central european characters..i found same subtitles on opensubtitles and i subtitle is ok again..
https://imgur.com/a/18rR5
it's a bummer..

**Comment by bokiroki** [comment]
also, why i get this message every time if i dont put encoding switches in my script? and it write 2 times..
Post processing subtitles Annihilation.2018.1080p.NF.WEBRip.DD5.1.x264-NTG.srt encoding.
https://imgur.com/a/IEMIP

**Comment by caronc** [comment]
> just few hours after i reported that i didn't found any problems, i downloaded movie with bad subtitle  i downloaded movie with radarr, radarr called your script.. i didn't put any -n and -e (encodings in script) and i got the same question marks on special central european  characters..i found same subtitle on opensubtitles and subtitle is ok  again.. https://imgur.com/a/18rR5 it's a bummer..

The screenshot you shared has to completely different subtitles (with completely different content in it).  You can't really compare them and say one is broken and the other isn't.

> also, why i get this message every time if i dont put encoding switches in my script? and it write 2 times..
Post processing subtitles Annihilation.2018.1080p.NF.WEBRip.DD5.1.x264-NTG.srt encoding.
https://imgur.com/a/IEMIP

If it's writing 'Post processing' then you still have the **-t** switch set (or **--tidy-subs**).  You'll also see this if you're still using the version before the one pushed in this ticket  Make sure you check out the [master branch](https://github.com/caronc/nzb-subliminal/archive/master.zip).  Another thing that could cause this is if you're using your own [custom configuration file](https://github.com/caronc/nzb-subliminal/wiki/Subliminal-Configuration-File) and TidySub is set to True.

**Comment by bokiroki** [comment]
Hi.. no, the subtitles in screenshot are the same.. only difference is that when subtitle is downloaded with nzb subliminal, first line in subtitles is added and it says:" advertise your product or brand with us, contact www.opensubtitles.org (i mentioned this earlier on issue thread), when i download subtitle on opensubtitle.org site, i dont get this line.. so line 1 on left subtitle is the same on line 2 on right subtitle, and so on..
this is my cofiguration.. i download you default branch, which is master (that is updated 30 minutes ago)
unzip it, and put nzb-subliminal-master folder on my raspberry pi..
then i create script with this switches

#!/bin/bash

python /home/dietpi/nzb-subliminal-master/Subliminal.py -f -s -l sr,hr -p podnapisi,opensubtitles -S /mnt/dietpi_userdata/MiniDLNA

and i make it executable

chmod +x /home/dietpi/nzb-subliminal-master/translate.sh

and put that script in my radarr..
thats all..

**Comment by caronc** [comment]
> that is updated 30 minutes ago

Yeah i pushed a small change to enforce the TidySub option is off for SABnzbd users; this won't impact your issue but it was related to it (so i referenced this ticket).

>  i create script with this switches

If you're seeing the text 'Post processed subtitles' then for some reason you're still set up to run the tidysubs option which is why it seems like you're running an older version.  Your script you're using looks good though!

When you use Open-Subtitles, you probably log into the website (which is why the content is different).  It's possible that Open-Subtitles is also changing the content (as clearly they have 2 subtitles to share, one with advertising and one without). It's possible the issue is here too.

**Comment by bokiroki** [comment]
i don't know, i never put -t switch, i dont even know what tidy do..only put -f -s -l -p and -S..
and i always delete old nzb-subliminal-master folder before downloading and testing new version..
also, i dont have opensubtitles account, so i dont log in to their site, but yes, maybe they have two types if subtitle..

**Comment by caronc** [comment]
@bokiroki ,

Can you confirm if the issue is still happening after the latest commit?  if it is, i may need you to capture some traces for me (running the script with a **-D** added to it).

**Comment by bokiroki** [comment]
I just tried, latest commit is from 7 days ago.. deleted old folder, downloaded new one, tried, and again i have question marks..and then i put -D sign and tried again.. in txt file i copied debug text..
[nzb debug.txt](https://github.com/caronc/nzb-subliminal/files/1845237/nzb.debug.txt)

**Comment by caronc** [comment]
I think i found what was going on! Thank you for sharing your debug information; that really helped!

**Comment by bokiroki** [comment]
Thank you.. i just tested new version, there are no more post processing messages.. perfect
