### ISSUE TITLE
Error launching from Sabnzb

### ISSUE THREAD

**Issue by francesco2013** [caronc/nzb-subliminal#53]
Script returned exit code 1 and output "Traceback (most recent call last): File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal.py", line 395, in <module> from apprise import Apprise File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/apprise/__init__.py", line 31, in <module> from .plugins.NotifyBase import NotifyBase File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/apprise/plugins/__init__.py", line 23, in <module> from .NotifyBoxcar import NotifyBoxcar File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/apprise/plugins/NotifyBoxcar.py", line 20, in <module> import requests File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/requests/__init__.py", line 53, in <module> from urllib3.contrib import pyopenssl File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/urllib3/contrib/pyopenssl.py", line 53, in <module> import OpenSSL.SSL File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/OpenSSL/__init__.py", line 8, in <module> from OpenSSL import rand, crypto, SSL File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/OpenSSL/SSL.py", line 112, in <module> if _lib.Cryptography_HAS_SSL_ST: AttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST' "

**From the command line**: 

./Subliminal.py
Traceback (most recent call last):
  File "./Subliminal.py", line 395, in <module>
    from apprise import Apprise
  File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/apprise/__init__.py", line 31, in <module>
    from .plugins.NotifyBase import NotifyBase
  File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/apprise/plugins/__init__.py", line 23, in <module>
    from .NotifyBoxcar import NotifyBoxcar
  File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/apprise/plugins/NotifyBoxcar.py", line 20, in <module>
    import requests
  File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/requests/__init__.py", line 53, in <module>
    from urllib3.contrib import pyopenssl
  File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/urllib3/contrib/pyopenssl.py", line 53, in <module>
    import OpenSSL.SSL
  File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/OpenSSL/SSL.py", line 112, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST'

**I am using Ubuntu 16.04**

**Comment by caronc** [comment]
This is a result of having a copy of Cryptography installed (globally to Ubuntu) that is conflicting with the copy of OpenSSL i ship with subliminal.

As a test, can you just delete the OpenSSL directory inside of the Subliminal directory? So in your case, you'll want to delete the directory:
```/root/sabnzbd-2.1.0/scripts/nzb-subliminal/Subliminal/OpenSSL```

This will cause Subliminal to use the global copy of OpenSSL you have installed instead.

Good luck!

**Comment by caronc** [comment]
I just wanted to ping you and get a status update?  Were you able to resolve your issue? Let me know so I can close off this ticket or we can proceed to troubleshoot more.

**Comment by caronc** [comment]
I still haven't heard back so i'm just going to close this ticket.  If you still have problems feel free to add a comment here.
