### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by eikaramba** [caronc/nzb-subliminal#66]
getting syntax error recently. any idea why that could be? using phyton 3.7.0 on windows x64
```
File "C:\Program Files\Media\nzbget-subliminal\Subliminal.py", line 433
    except OSError, e:
                  ^
SyntaxError: invalid syntax
```

**Comment by caronc** [comment]
Unfortunately this script isn't compatible with Python 3. You need to use Python 2.7 instead.

**Comment by eikaramba** [comment]
ah ok thx. solved it by renaming python.exe (version 2) binary to python2.exe and then doing
python2 "pathtolib\Subliminal.py"

works :)
