### ISSUE TITLE
Do you support composite language codes?

### ISSUE THREAD

**Issue by msdos** [caronc/nzb-subliminal#67]
`subliminal` accepts `pt-br`, but your script only accepts `pt`. Is this the intended behavior?

**Comment by caronc** [comment]
Yeah, the issue isn't so much the script, but the fact that most of the actual subtitle websites don't support the composite IDs either. :pensive:

**Comment by caronc** [comment]
Hi, I'm just going to close this ticket as i hadn't heard back.

Feel free to re-open it and/or comment on it if you have any more questions.
