### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jst1102** [caronc/nzb-subliminal#71]
when trying to download subtitles, i'm getting this error:

File "Subliminal.py", line 2435
    except ConfigException, e:
                          ^
SyntaxError: invalid syntax

when i run this command:

python Subliminal.py -s -f e:\Shows e:\Movies

I have subliminal in my scripts folder for sabnzbd and the subliminal.py script too. Is something wrong with the .py or am i doing something incorrect?

**Comment by caronc** [comment]
What version of Python are you using? *NZB-Subliminal* unfortunately doesn't support v3 (yet).

**Comment by jst1102** [comment]
ahhhh - i am using v 3.7, should i downgrade??? i'm using that for my
django project though, i think i can use a different version to accomplish
this without downgrading, right? sorry, haven't had to deal with it yet.
thanks for replying.

**Comment by caronc** [comment]
Unfortunately yeah, this is the only NZBGet plugin i haven't ported to Python 3 yet; sorry :slightly_frowning_face: 

Are you just using this script from the command line? Or are you connecting it up to NZBGet?  If you're just using the command line functionality of it, you could check out the official [Subliminal tool](https://github.com/Diaoul/subliminal) which supports Python v3.

**Comment by jst1102** [comment]
ah, i was trying to connect it to sabnzdb and do a cron job if i got it to
work. Good suggestion though! i'll check it out

**Comment by caronc** [comment]
SABnzbd uses Python 2 as far as i know right now; so if it works, you definitely have the tools already to make this script work too (if you need to fall back).

Either way, I'll let you close this ticket when your comfortable. I don't mind answering any other questions you might have otherwise.

Good luck!

**Comment by jst1102** [comment]
good news, i figured out how to do this:

from the cmd:

reference your old python v2 .exe  first, then perform the desired command
for the subminial wrapper you've created, e.g.:

C:\Program Files\SABnzbd\scripts>C:\python27\python Subliminal.py -s -f
e:\Movies e:\Shows

here i am in the folder for the sabnzbd scripts as suggested, reference the
python v2 exe, then perform the python command. It worked like a charm!
Must have v2 of python installed separately from v3 for it to work.

now to figure out how to run the cron job...

i'll put this up in the ticket

**Comment by jst1102** [comment]
Closing for now. If anyone can figure out the cron job, that's just icing on the cake
