### ISSUE TITLE
How do I specify opensubtitles username/password in Subliminal.ini?

### ISSUE THREAD

**Issue by mkanet** [caronc/nzb-subliminal#76]
:question: **Question**

Is the only way to specify opensubtitles username/password via command line; or, is there a way to do it via the ini file as well?  I didn't see any examples in the ini file for opensubtitles username/password, only addic7ed username, and password.

Also, I keep seeing the warning message below while running the script against my TV and Movies directories.  I have already specified the correct username and password for Addic7ed.  I have tried specifying the correct username and password in the ini only, command-line only, and both ini and command-line.

`WARNING - Failed to authenticate with Addic7ed!`

**Comment by caronc** [comment]
This project is somewhat abandoned unfortunately.  You could try [this branch](https://github.com/caronc/nzb-subliminal/tree/51-adding-more-search-providers) which never got merged to the master as it has some issues of it's own, but I believe it supports the authentication part you're looking for. 

Unfortunately i haven't touched this code in 2+ years and I'm not sure when/if I'll get around to it or not. There are great alternatives out there though. You could check out [Bazarr](https://github.com/morpheus65535/bazarr).

**Comment by mkanet** [comment]
Thanks.  I saw Bazarr.  However, I didn't like the idea of having yet other full time service always running in the background unnecessarily. A sabnzbd script sound much more appealing.  Of course, the issue is moot if the script is broken/unsupported.

**Comment by mkanet** [comment]
Is there an alternative like this one that can be called from command line?

**Comment by caronc** [comment]
This still works from the command line as long as you're using Python v2.x :slightly_smiling_face: .  There is [the original Subliminal tool](https://github.com/Diaoul/subliminal) itself that this fork extended from too you could try. It just had a release to it in May 2020; so it's good to see it's still getting some development time put to it.

**Comment by mkanet** [comment]
Thank you for your help.  I decided to go with your original advice to use Bazarr.  It's very easy to install.. and, seems very feature-rich.  Seems like the best solution for me.
